from datetime import datetime
from halo import Halo
import argparse
import os
from itertools import product
from tqdm import tqdm

from utils.random_location_Generator import random_locations
from utils.sun_localizer import SunLocalizer

def create_error_combinations(degrees_error=0):
    """
    Generate all combinations of error offsets for solar azimuth and elevation
    angles.

    Parameters
    ----------
    degrees_error : int
        The number of degrees of error to add to the solar azimuth and
        elevation angles.

    Returns
    -------
    list
        A list of tuples, where each tuple contains the error offset for
        the solar azimuth and elevation angles.
    """
    l1 = [x for x in range(-degrees_error, degrees_error + 1)]
    l2 = [x for x in range(-degrees_error, degrees_error + 1)]
    return list(product(l1, l2))

def generate_random_config(num_locations, datetime_rt):
    """
    Generate a random configuration file.

    Parameters
    ----------
    num_locations : int
        The number of random locations to generate.
    datetime_rt : str
        The current datetime in UTC timezone.

    Returns
    -------
    str
        The path to the generated random configuration file.
    """
    spinner = Halo(text='Generating random locations', spinner='dots')
    spinner.start()
    os.makedirs("random_location_csvs", exist_ok=True)
    file_name = os.path.join("random_location_csvs", f"{datetime_rt}.csv")
    random_locations(num_locations, file_name)
    spinner.stop()
    return file_name

def run_localizer(args, datetime_rt):
    """
    Run the solar location finder on either a config file or a pandas dataframe.

    If `degrees_of_error` is greater than 0, the function will run the solar location
    finder multiple times with different error offsets for the solar azimuth and
    elevation angles. The error offsets are generated by the
    `create_error_combinations` function.

    If `degrees_of_error` is 0, the function will run the solar location finder once
    with no error offset.

    Parameters
    ----------
    args : argparse.Namespace
        The parsed command line arguments.
    datetime_rt : str
        The current datetime in UTC timezone.
    """
    if args.doe > 0:
        error_combinations = create_error_combinations(args.doe)
        for combo in tqdm(error_combinations, desc="Running solar location finder with different error offsets"):
            sun_localizer = SunLocalizer(args, datetime_rt)
            sun_localizer.find_me(*combo)
    else:
        sun_localizer = SunLocalizer(args, datetime_rt)
        sun_localizer.find_me()

def parse_args():
    """
    Parse command line arguments and return them as an object.

    Returns
    -------
    argparse.Namespace
        An object containing the parsed command line arguments.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", type=str, help="Path to the YAML configuration file")
    parser.add_argument("--random", type=int, help="Number of random locations to run on")
    parser.add_argument("--skip_map", action="store_true", help="Skip map generation")
    parser.add_argument("--open_map", action="store_true", help="Open the map in a web browser")
    parser.add_argument("--agent_description", action="store_true", help="Print navigation description")
    parser.add_argument("--doe", type=int, default=0, 
                        help="Degrees of error (doe). Range of degrees to test maximum allowed error")
    return parser.parse_args()

def main():
    """
    The main entry point of the script.

    This function parses the command line arguments and calls the
    `run_localizer` function to run the solar location finder.
    """
    datetime_rt = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    os.makedirs(os.path.join("results", datetime_rt), exist_ok=True)
    args = parse_args()
    if args.random:
        args.config = generate_random_config(args.random, datetime_rt)

    run_localizer(args, datetime_rt)


if __name__ == "__main__":
    main()
